/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as PortalPerfilRouteImport } from './routes/portal.perfil'
import { Route as PortalNotificacionesRouteImport } from './routes/portal.notificaciones'
import { Route as PortalMascotasRouteImport } from './routes/portal.mascotas'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalAgendaRouteImport } from './routes/portal.agenda'
import { Route as AppWebsiteRouteImport } from './routes/_app.website'
import { Route as AppVeterinariosRouteImport } from './routes/_app.veterinarios'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppServiciosRouteImport } from './routes/_app.servicios'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppPuntoVentaRouteImport } from './routes/_app.punto-venta'
import { Route as AppPosVentasRouteImport } from './routes/_app.pos-ventas'
import { Route as AppPosProductosRouteImport } from './routes/_app.pos-productos'
import { Route as AppPosPedidosRouteImport } from './routes/_app.pos-pedidos'
import { Route as AppPosOnlineRouteImport } from './routes/_app.pos-online'
import { Route as AppPosMovimientosRouteImport } from './routes/_app.pos-movimientos'
import { Route as AppPosCategoriasRouteImport } from './routes/_app.pos-categorias'
import { Route as AppPosCajaRouteImport } from './routes/_app.pos-caja'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppMascotasRouteImport } from './routes/_app.mascotas'
import { Route as AppInventarioRouteImport } from './routes/_app.inventario'
import { Route as AppHospitalizacionRouteImport } from './routes/_app.hospitalizacion'
import { Route as AppFacturacionRouteImport } from './routes/_app.facturacion'
import { Route as AppEspeciesRouteImport } from './routes/_app.especies'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConsultasRouteImport } from './routes/_app.consultas'
import { Route as AppConfiguracionRouteImport } from './routes/_app.configuracion'
import { Route as AppClinicasRouteImport } from './routes/_app.clinicas'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppCajaRouteImport } from './routes/_app.caja'
import { Route as AppAutomatizacionRouteImport } from './routes/_app.automatizacion'
import { Route as AppAjustesRouteImport } from './routes/_app.ajustes'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPerfilRoute = PortalPerfilRouteImport.update({
  id: '/portal/perfil',
  path: '/portal/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalNotificacionesRoute = PortalNotificacionesRouteImport.update({
  id: '/portal/notificaciones',
  path: '/portal/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMascotasRoute = PortalMascotasRouteImport.update({
  id: '/portal/mascotas',
  path: '/portal/mascotas',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/portal/dashboard',
  path: '/portal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAgendaRoute = PortalAgendaRouteImport.update({
  id: '/portal/agenda',
  path: '/portal/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebsiteRoute = AppWebsiteRouteImport.update({
  id: '/_app/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVeterinariosRoute = AppVeterinariosRouteImport.update({
  id: '/_app/veterinarios',
  path: '/veterinarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/_app/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServiciosRoute = AppServiciosRouteImport.update({
  id: '/_app/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/_app/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPuntoVentaRoute = AppPuntoVentaRouteImport.update({
  id: '/_app/punto-venta',
  path: '/punto-venta',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPosVentasRoute = AppPosVentasRouteImport.update({
  id: '/_app/pos-ventas',
  path: '/pos-ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPosProductosRoute = AppPosProductosRouteImport.update({
  id: '/_app/pos-productos',
  path: '/pos-productos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPosPedidosRoute = AppPosPedidosRouteImport.update({
  id: '/_app/pos-pedidos',
  path: '/pos-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPosOnlineRoute = AppPosOnlineRouteImport.update({
  id: '/_app/pos-online',
  path: '/pos-online',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPosMovimientosRoute = AppPosMovimientosRouteImport.update({
  id: '/_app/pos-movimientos',
  path: '/pos-movimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPosCategoriasRoute = AppPosCategoriasRouteImport.update({
  id: '/_app/pos-categorias',
  path: '/pos-categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPosCajaRoute = AppPosCajaRouteImport.update({
  id: '/_app/pos-caja',
  path: '/pos-caja',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/_app/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMascotasRoute = AppMascotasRouteImport.update({
  id: '/_app/mascotas',
  path: '/mascotas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventarioRoute = AppInventarioRouteImport.update({
  id: '/_app/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHospitalizacionRoute = AppHospitalizacionRouteImport.update({
  id: '/_app/hospitalizacion',
  path: '/hospitalizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFacturacionRoute = AppFacturacionRouteImport.update({
  id: '/_app/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEspeciesRoute = AppEspeciesRouteImport.update({
  id: '/_app/especies',
  path: '/especies',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/_app/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConsultasRoute = AppConsultasRouteImport.update({
  id: '/_app/consultas',
  path: '/consultas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/_app/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClinicasRoute = AppClinicasRouteImport.update({
  id: '/_app/clinicas',
  path: '/clinicas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/_app/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCajaRoute = AppCajaRouteImport.update({
  id: '/_app/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAutomatizacionRoute = AppAutomatizacionRouteImport.update({
  id: '/_app/automatizacion',
  path: '/automatizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAjustesRoute = AppAjustesRouteImport.update({
  id: '/_app/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/_app/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/_app/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tienda': typeof TiendaRoute
  '/admin': typeof AppAdminRoute
  '/agenda': typeof AppAgendaRoute
  '/ajustes': typeof AppAjustesRoute
  '/automatizacion': typeof AppAutomatizacionRoute
  '/caja': typeof AppCajaRoute
  '/clientes': typeof AppClientesRoute
  '/clinicas': typeof AppClinicasRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/consultas': typeof AppConsultasRoute
  '/dashboard': typeof AppDashboardRoute
  '/especies': typeof AppEspeciesRoute
  '/facturacion': typeof AppFacturacionRoute
  '/hospitalizacion': typeof AppHospitalizacionRoute
  '/inventario': typeof AppInventarioRoute
  '/mascotas': typeof AppMascotasRoute
  '/perfil': typeof AppPerfilRoute
  '/pos-caja': typeof AppPosCajaRoute
  '/pos-categorias': typeof AppPosCategoriasRoute
  '/pos-movimientos': typeof AppPosMovimientosRoute
  '/pos-online': typeof AppPosOnlineRoute
  '/pos-pedidos': typeof AppPosPedidosRoute
  '/pos-productos': typeof AppPosProductosRoute
  '/pos-ventas': typeof AppPosVentasRoute
  '/punto-venta': typeof AppPuntoVentaRoute
  '/roles': typeof AppRolesRoute
  '/servicios': typeof AppServiciosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/veterinarios': typeof AppVeterinariosRoute
  '/website': typeof AppWebsiteRoute
  '/portal/agenda': typeof PortalAgendaRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/mascotas': typeof PortalMascotasRoute
  '/portal/notificaciones': typeof PortalNotificacionesRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/site/$slug': typeof SiteSlugRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tienda': typeof TiendaRoute
  '/admin': typeof AppAdminRoute
  '/agenda': typeof AppAgendaRoute
  '/ajustes': typeof AppAjustesRoute
  '/automatizacion': typeof AppAutomatizacionRoute
  '/caja': typeof AppCajaRoute
  '/clientes': typeof AppClientesRoute
  '/clinicas': typeof AppClinicasRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/consultas': typeof AppConsultasRoute
  '/dashboard': typeof AppDashboardRoute
  '/especies': typeof AppEspeciesRoute
  '/facturacion': typeof AppFacturacionRoute
  '/hospitalizacion': typeof AppHospitalizacionRoute
  '/inventario': typeof AppInventarioRoute
  '/mascotas': typeof AppMascotasRoute
  '/perfil': typeof AppPerfilRoute
  '/pos-caja': typeof AppPosCajaRoute
  '/pos-categorias': typeof AppPosCategoriasRoute
  '/pos-movimientos': typeof AppPosMovimientosRoute
  '/pos-online': typeof AppPosOnlineRoute
  '/pos-pedidos': typeof AppPosPedidosRoute
  '/pos-productos': typeof AppPosProductosRoute
  '/pos-ventas': typeof AppPosVentasRoute
  '/punto-venta': typeof AppPuntoVentaRoute
  '/roles': typeof AppRolesRoute
  '/servicios': typeof AppServiciosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/veterinarios': typeof AppVeterinariosRoute
  '/website': typeof AppWebsiteRoute
  '/portal/agenda': typeof PortalAgendaRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/mascotas': typeof PortalMascotasRoute
  '/portal/notificaciones': typeof PortalNotificacionesRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/site/$slug': typeof SiteSlugRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tienda': typeof TiendaRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/ajustes': typeof AppAjustesRoute
  '/_app/automatizacion': typeof AppAutomatizacionRoute
  '/_app/caja': typeof AppCajaRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/clinicas': typeof AppClinicasRoute
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/consultas': typeof AppConsultasRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/especies': typeof AppEspeciesRoute
  '/_app/facturacion': typeof AppFacturacionRoute
  '/_app/hospitalizacion': typeof AppHospitalizacionRoute
  '/_app/inventario': typeof AppInventarioRoute
  '/_app/mascotas': typeof AppMascotasRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/pos-caja': typeof AppPosCajaRoute
  '/_app/pos-categorias': typeof AppPosCategoriasRoute
  '/_app/pos-movimientos': typeof AppPosMovimientosRoute
  '/_app/pos-online': typeof AppPosOnlineRoute
  '/_app/pos-pedidos': typeof AppPosPedidosRoute
  '/_app/pos-productos': typeof AppPosProductosRoute
  '/_app/pos-ventas': typeof AppPosVentasRoute
  '/_app/punto-venta': typeof AppPuntoVentaRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/servicios': typeof AppServiciosRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/veterinarios': typeof AppVeterinariosRoute
  '/_app/website': typeof AppWebsiteRoute
  '/portal/agenda': typeof PortalAgendaRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/mascotas': typeof PortalMascotasRoute
  '/portal/notificaciones': typeof PortalNotificacionesRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/site/$slug': typeof SiteSlugRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tienda'
    | '/admin'
    | '/agenda'
    | '/ajustes'
    | '/automatizacion'
    | '/caja'
    | '/clientes'
    | '/clinicas'
    | '/configuracion'
    | '/consultas'
    | '/dashboard'
    | '/especies'
    | '/facturacion'
    | '/hospitalizacion'
    | '/inventario'
    | '/mascotas'
    | '/perfil'
    | '/pos-caja'
    | '/pos-categorias'
    | '/pos-movimientos'
    | '/pos-online'
    | '/pos-pedidos'
    | '/pos-productos'
    | '/pos-ventas'
    | '/punto-venta'
    | '/roles'
    | '/servicios'
    | '/usuarios'
    | '/veterinarios'
    | '/website'
    | '/portal/agenda'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/mascotas'
    | '/portal/notificaciones'
    | '/portal/perfil'
    | '/site/$slug'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tienda'
    | '/admin'
    | '/agenda'
    | '/ajustes'
    | '/automatizacion'
    | '/caja'
    | '/clientes'
    | '/clinicas'
    | '/configuracion'
    | '/consultas'
    | '/dashboard'
    | '/especies'
    | '/facturacion'
    | '/hospitalizacion'
    | '/inventario'
    | '/mascotas'
    | '/perfil'
    | '/pos-caja'
    | '/pos-categorias'
    | '/pos-movimientos'
    | '/pos-online'
    | '/pos-pedidos'
    | '/pos-productos'
    | '/pos-ventas'
    | '/punto-venta'
    | '/roles'
    | '/servicios'
    | '/usuarios'
    | '/veterinarios'
    | '/website'
    | '/portal/agenda'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/mascotas'
    | '/portal/notificaciones'
    | '/portal/perfil'
    | '/site/$slug'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/tienda'
    | '/_app/admin'
    | '/_app/agenda'
    | '/_app/ajustes'
    | '/_app/automatizacion'
    | '/_app/caja'
    | '/_app/clientes'
    | '/_app/clinicas'
    | '/_app/configuracion'
    | '/_app/consultas'
    | '/_app/dashboard'
    | '/_app/especies'
    | '/_app/facturacion'
    | '/_app/hospitalizacion'
    | '/_app/inventario'
    | '/_app/mascotas'
    | '/_app/perfil'
    | '/_app/pos-caja'
    | '/_app/pos-categorias'
    | '/_app/pos-movimientos'
    | '/_app/pos-online'
    | '/_app/pos-pedidos'
    | '/_app/pos-productos'
    | '/_app/pos-ventas'
    | '/_app/punto-venta'
    | '/_app/roles'
    | '/_app/servicios'
    | '/_app/usuarios'
    | '/_app/veterinarios'
    | '/_app/website'
    | '/portal/agenda'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/mascotas'
    | '/portal/notificaciones'
    | '/portal/perfil'
    | '/site/$slug'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TiendaRoute: typeof TiendaRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppAjustesRoute: typeof AppAjustesRoute
  AppAutomatizacionRoute: typeof AppAutomatizacionRoute
  AppCajaRoute: typeof AppCajaRoute
  AppClientesRoute: typeof AppClientesRoute
  AppClinicasRoute: typeof AppClinicasRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppConsultasRoute: typeof AppConsultasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEspeciesRoute: typeof AppEspeciesRoute
  AppFacturacionRoute: typeof AppFacturacionRoute
  AppHospitalizacionRoute: typeof AppHospitalizacionRoute
  AppInventarioRoute: typeof AppInventarioRoute
  AppMascotasRoute: typeof AppMascotasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPosCajaRoute: typeof AppPosCajaRoute
  AppPosCategoriasRoute: typeof AppPosCategoriasRoute
  AppPosMovimientosRoute: typeof AppPosMovimientosRoute
  AppPosOnlineRoute: typeof AppPosOnlineRoute
  AppPosPedidosRoute: typeof AppPosPedidosRoute
  AppPosProductosRoute: typeof AppPosProductosRoute
  AppPosVentasRoute: typeof AppPosVentasRoute
  AppPuntoVentaRoute: typeof AppPuntoVentaRoute
  AppRolesRoute: typeof AppRolesRoute
  AppServiciosRoute: typeof AppServiciosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVeterinariosRoute: typeof AppVeterinariosRoute
  AppWebsiteRoute: typeof AppWebsiteRoute
  PortalAgendaRoute: typeof PortalAgendaRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalMascotasRoute: typeof PortalMascotasRoute
  PortalNotificacionesRoute: typeof PortalNotificacionesRoute
  PortalPerfilRoute: typeof PortalPerfilRoute
  SiteSlugRoute: typeof SiteSlugRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/perfil': {
      id: '/portal/perfil'
      path: '/portal/perfil'
      fullPath: '/portal/perfil'
      preLoaderRoute: typeof PortalPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/notificaciones': {
      id: '/portal/notificaciones'
      path: '/portal/notificaciones'
      fullPath: '/portal/notificaciones'
      preLoaderRoute: typeof PortalNotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/mascotas': {
      id: '/portal/mascotas'
      path: '/portal/mascotas'
      fullPath: '/portal/mascotas'
      preLoaderRoute: typeof PortalMascotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/agenda': {
      id: '/portal/agenda'
      path: '/portal/agenda'
      fullPath: '/portal/agenda'
      preLoaderRoute: typeof PortalAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/website': {
      id: '/_app/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof AppWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/veterinarios': {
      id: '/_app/veterinarios'
      path: '/veterinarios'
      fullPath: '/veterinarios'
      preLoaderRoute: typeof AppVeterinariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/servicios': {
      id: '/_app/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof AppServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/punto-venta': {
      id: '/_app/punto-venta'
      path: '/punto-venta'
      fullPath: '/punto-venta'
      preLoaderRoute: typeof AppPuntoVentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pos-ventas': {
      id: '/_app/pos-ventas'
      path: '/pos-ventas'
      fullPath: '/pos-ventas'
      preLoaderRoute: typeof AppPosVentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pos-productos': {
      id: '/_app/pos-productos'
      path: '/pos-productos'
      fullPath: '/pos-productos'
      preLoaderRoute: typeof AppPosProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pos-pedidos': {
      id: '/_app/pos-pedidos'
      path: '/pos-pedidos'
      fullPath: '/pos-pedidos'
      preLoaderRoute: typeof AppPosPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pos-online': {
      id: '/_app/pos-online'
      path: '/pos-online'
      fullPath: '/pos-online'
      preLoaderRoute: typeof AppPosOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pos-movimientos': {
      id: '/_app/pos-movimientos'
      path: '/pos-movimientos'
      fullPath: '/pos-movimientos'
      preLoaderRoute: typeof AppPosMovimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pos-categorias': {
      id: '/_app/pos-categorias'
      path: '/pos-categorias'
      fullPath: '/pos-categorias'
      preLoaderRoute: typeof AppPosCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pos-caja': {
      id: '/_app/pos-caja'
      path: '/pos-caja'
      fullPath: '/pos-caja'
      preLoaderRoute: typeof AppPosCajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/mascotas': {
      id: '/_app/mascotas'
      path: '/mascotas'
      fullPath: '/mascotas'
      preLoaderRoute: typeof AppMascotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inventario': {
      id: '/_app/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AppInventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/hospitalizacion': {
      id: '/_app/hospitalizacion'
      path: '/hospitalizacion'
      fullPath: '/hospitalizacion'
      preLoaderRoute: typeof AppHospitalizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/facturacion': {
      id: '/_app/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof AppFacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/especies': {
      id: '/_app/especies'
      path: '/especies'
      fullPath: '/especies'
      preLoaderRoute: typeof AppEspeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/consultas': {
      id: '/_app/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof AppConsultasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clinicas': {
      id: '/_app/clinicas'
      path: '/clinicas'
      fullPath: '/clinicas'
      preLoaderRoute: typeof AppClinicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/caja': {
      id: '/_app/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof AppCajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/automatizacion': {
      id: '/_app/automatizacion'
      path: '/automatizacion'
      fullPath: '/automatizacion'
      preLoaderRoute: typeof AppAutomatizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ajustes': {
      id: '/_app/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AppAjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TiendaRoute: TiendaRoute,
  AppAdminRoute: AppAdminRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppAjustesRoute: AppAjustesRoute,
  AppAutomatizacionRoute: AppAutomatizacionRoute,
  AppCajaRoute: AppCajaRoute,
  AppClientesRoute: AppClientesRoute,
  AppClinicasRoute: AppClinicasRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppConsultasRoute: AppConsultasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEspeciesRoute: AppEspeciesRoute,
  AppFacturacionRoute: AppFacturacionRoute,
  AppHospitalizacionRoute: AppHospitalizacionRoute,
  AppInventarioRoute: AppInventarioRoute,
  AppMascotasRoute: AppMascotasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPosCajaRoute: AppPosCajaRoute,
  AppPosCategoriasRoute: AppPosCategoriasRoute,
  AppPosMovimientosRoute: AppPosMovimientosRoute,
  AppPosOnlineRoute: AppPosOnlineRoute,
  AppPosPedidosRoute: AppPosPedidosRoute,
  AppPosProductosRoute: AppPosProductosRoute,
  AppPosVentasRoute: AppPosVentasRoute,
  AppPuntoVentaRoute: AppPuntoVentaRoute,
  AppRolesRoute: AppRolesRoute,
  AppServiciosRoute: AppServiciosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVeterinariosRoute: AppVeterinariosRoute,
  AppWebsiteRoute: AppWebsiteRoute,
  PortalAgendaRoute: PortalAgendaRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalMascotasRoute: PortalMascotasRoute,
  PortalNotificacionesRoute: PortalNotificacionesRoute,
  PortalPerfilRoute: PortalPerfilRoute,
  SiteSlugRoute: SiteSlugRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
